twitter:
  domain: https://api.twitter.com
  bearer: override

twitter-api:
  timeline:
    v1-user-path: /1.1/statuses/user_timeline.json
    v2-user-path: /2/users/{id}/tweets
  user:
    lookup-path: /2/users/by/username/{username}
