spring:
  profiles:
    active: prod

twitter-api:
  timeline:
    domain: https://api.twitter.com
    user-path: /1.1/statuses/user_timeline.json
  user:
    domain: https://api.twitter.com
    lookup-path: /2/users/by/username/{username}