twitter:
  domain: https://api.twitter.com
  bearer: override
  auth:
    key: override
    secret: override
    callback: http://127.0.0.1/auth
    requestu-token-path: /oauth/request_token

twitter-api:
  timeline:
    v1-user-path: /1.1/statuses/user_timeline.json
    v2-user-path: /2/users/{id}/tweets
  user:
    lookup-path: /2/users/by/username/{username}
